sudo: false
dist: bionic
language: go

matrix:
  include:
    - env: TEST=build-local
      go: 1.11
      script:
        - go build .
        - go test -v ./...
    - env: TEST=build-local
      go: 1.12
      script:
        - go build .
        - go test -v ./...
    - env: TEST=build-local
      go: 1.13
      script:
        - go build .
        - go test -v ./...
    - env: TEST=build-local
      go: 1.14
      script:
        - go build .
        - go test -v ./...
    - env: TEST=build-xgo-linux
      sudo: true
      script:
        - docker pull karalabe/xgo-latest
        - go get github.com/karalabe/xgo
        - cd release/linux
        - make all
    - env: TEST=build-xgo-windows
      sudo: true
      script:
        - docker pull karalabe/xgo-latest
        - go get github.com/karalabe/xgo
        - cd release/windows
        - make all
    - env: TEST=build-xgo-macos
      sudo: true
      script:
        - docker pull karalabe/xgo-latest
        - go get github.com/karalabe/xgo
        - cd release/macos
        - make all
    - env: TEST=go-vet
      script:
        - go vet ./...
    - env: TEST=go-fmt
      script:
        - gofmt -d *.go ./server ./server/status ./server/api ./usb ./wire ./core ./memorywriter
    - env: TEST=metalinter
      script:
        - go get -u github.com/alecthomas/gometalinter
        - gometalinter --install
        - gometalinter
    - env: TEST=version-check
      script:
        - diff -u VERSION <(grep "const version" onekey.go | cut -f 2 -d '"')

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
